language: php
sudo: false
php:
  - 7.0.28
  - 7.1.15
  - 7.2.3
  - hhvm
  - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
os:
    - windows
    - linux
install:
    - travis_retry composer install --no-interaction
script:
    - ./vendor/bin/phpcs --standard=psr2 src/
    - ./vendor/bin/phpunit --coverage-text
    - ./vendor/bin/psalm
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
